skeleton: Fix NoClassDefFoundError-s in core.tests
Add the missing . (dot, current directory include) line to the skeleton
core's build.properties, to fix NoClassDefFoundError(s) in plugin tests.

[Fixed] Bug 574542: Fix NoClassDefFoundError-s in core.tests

Change-Id: I79eb291fa35d4e75b8a0e91e5bdada3188d08c26
Signed-off-by: Marco Miller <marco.miller@ericsson.com>
Reviewed-on: https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/182611
Tested-by: Trace Compass Bot <tracecompass-bot@eclipse.org>
Tested-by: Matthew Khouzam <matthew.khouzam@ericsson.com>
Tested-by: Bernd Hufmann <bernd.hufmann@ericsson.com>
Reviewed-by: Matthew Khouzam <matthew.khouzam@ericsson.com>
Reviewed-by: Bernd Hufmann <bernd.hufmann@ericsson.com>